name: Push to External Repo

on:
  push:
    branches:
      - 'irn-releases'    # or restrict to a specific branch
    paths-ignore: 
      - 'k8s/**' 
      - '.gitattributes'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove .github directory
        run: |
          rm -rf .github

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit removal of .github (temporary commit)
        run: |
          git add -A
          git commit -m "Prepare repo for sync (exclude .github)" || echo "No changes"

      - name: Add external repo and push
        run: |
          git remote add external https://oauth2:${{ secrets.EXT_REPO_PAT }}@code.irn.justica.gov.pt/plataforma-de-registos/backoffice-componentes-transversais/igrp-process-studio-frontend.git
          
          git push external HEAD:feature/zing-commits --force
